name: IvP SVN Mirror

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: "Install git-svn"
      run: |
        sudo add-apt-repository ppa:git-core/ppa
        sudo apt-get update && sudo apt-get install git git-svn
    - name: Restore svn cache
      id: cache
      uses: actions/cache@v4
      with:
        path: ivp-svn
        key: svncache
    - name: Clone SVN repo
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        git svn clone -r8000:HEAD --ignore-paths='(^MOOS.*|^ivp/src/lib_fltk.*|^ivp/data|^ivp/missions|^ivp/src/ATTIC|\.tgz$|^scripted-releases|^editor-modes|^moosdocs|^manifests)' https://oceanai.mit.edu/svn/moos-ivp-aro/trunk ivp-svn

    - name: Update from SVN
      run: |
        cd ivp-svn
        git svn fetch
        git svn rebase

    - name: Push new commits to mirror branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: mirror
        force: true
        directory: ivp-svn
